import React from "react"
// import avatarImg1 from "../../../assets/images/users/avatar-1.jpg"
// import avatarImg2 from "../../../assets/images/users/avatar-2.jpg"
// import avatarImg3 from "../../../assets/images/users/avatar-3.jpg"
// import avatarImg4 from "../../../assets/images/users/avatar-4.jpg"
// import avatarImg5 from "../../../assets/images/users/avatar-5.jpg"
// import avatarImg6 from "../../../assets/images/users/avatar-6.jpg"

export const EmployeeData = [
  {
    userId: "1",
    jobTitleName: "Developer",
    firstName: "Romin",
    lastName: "Irani",
    preferredFullName: "Romin Irani",
    employeeCode: "E1",
    phoneNumber: "408-1234567",
    emailAddress: "romin.k.irani@gmail.com",
    // userpic: avatarImg1,
    status: "Active",
    variant: "success",
    Department: "IT",
    Designation: "Senior Developer",
  },
  {
    userId: "2",
    jobTitleName: "Developer",
    firstName: "Neil",
    lastName: "Irani",
    preferredFullName: "Neil Irani",
    employeeCode: "E2",
    phoneNumber: "408-1111111",
    emailAddress: "neilrirani@gmail.com",
    // userpic: avatarImg2,
    status: "Active",
    variant: "success",
    Department: "HR",
    Designation: "HR Director",
  },
  {
    userId: "3",
    jobTitleName: "Program Directory",
    firstName: "Tom",
    lastName: "Hanks",
    preferredFullName: "Tom Hanks",
    employeeCode: "E3",
    phoneNumber: "408-2222222",
    emailAddress: "tomhanks@gmail.com",
    // userpic: avatarImg3,
    status: "Not-Active",
    variant: "danger",
    Department: "Accounts",
    Designation: "Junior Accountant",
  },
  {
    userId: "4",
    jobTitleName: "Developer",
    firstName: "Romin",
    lastName: "Irani",
    preferredFullName: " Stone Michel ",
    employeeCode: "E4",
    phoneNumber: "408-1234567",
    emailAddress: "romin.k.irani@gmail.com",
    // userpic: avatarImg4,
    status: "Active",
    variant: "success",
    Department: "IT",
    Designation: "Junior Developer",
  },
  {
    userId: "5",
    jobTitleName: "Developer",
    firstName: "Neil",
    lastName: "Irani",
    preferredFullName: "Andreson",
    employeeCode: "E5",
    phoneNumber: "408-1111111",
    emailAddress: "neilrirani@gmail.com",
    // userpic: avatarImg5,
    status: "Active",
    variant: "success",
    Department: "HR",
    Designation: "Intern Hr",
  },
  {
    userId: "6",
    jobTitleName: "Program Directory",
    firstName: "Tom",
    lastName: "Hanks",
    preferredFullName: "Tom Cruise",
    employeeCode: "E6",
    phoneNumber: "408-2222222",
    emailAddress: "tomhanks@gmail.com",
    // userpic: avatarImg6,
    status: "Not-Active",
    variant: "danger",
    Department: "IT",
    Designation: "Intern Developer",
  },
]
